### ISSUE TITLE
OpenOCD参数问题

### ISSUE THREAD

**Issue by pcbcos** [kaidegit/CH32V103_Template_ForCLion#1]
我观察了一下CLion在调用OpenOCD时执行的命令，似乎缺少了烧写地址的偏移值0x0800 0000，我加入了这个偏移值，在自己的控制台运行就能完成烧录，不知道能不能使CLion自动在它的命令中加入这个偏移值，谢谢。
![image](https://user-images.githubusercontent.com/29155762/151147621-c5fa26a9-6881-453e-9363-fb82e2c4fd72.png)

成功使用OpenOCD烧录
![QQ截图20220126182700](https://user-images.githubusercontent.com/29155762/151147673-d0f84c6c-d22e-4d8f-831c-bf052d969090.png)

**Comment by pcbcos** [comment]
![image](https://user-images.githubusercontent.com/29155762/151157031-c2957ca2-87f0-41fb-9ae4-389597159fc7.png)
我找到的一个办法是让CMake代劳执行这个烧写命令

**Comment by kaidegit** [comment]
嗨：

我将链接文件中flash位置从0x0改到了0x0800 0000，稍微改了改启动文件，然后换了新的openocd，似乎可以了。

参考链接：http://www.wch.cn/bbs/thread-72771-1.html

**Comment by pcbcos** [comment]
学到了，谢谢
